main: me.Joey.CommandsPlus.Main
name: Commands_Plus
version: 1.9
api-version: 1.13
author: Joey_Balardeta


commands:
  C+help:
  Talents:
  Reeval:
  Vanillamode:
  Cords:
  Claim:
  Unclaim:
  Chunkname:
  Whochunk:
  Chunkmap:
  Faction:
  Level:
  Scoreboard:
  Creator:
  Credits:
  Bonkstick:
  Yeehaw: