main: me.Joey.CommandsPlus.Main
name: Commands_Plus
version: 3.0
api-version: 1.13
author: Joey_Balardeta


commands:
  C+help:
  Test:
  Reeval:
  Vanillamode:
  Cords:
  Claim:
  Unclaim:
  Chunkname:
  Whochunk:
  Chunkmap:
  Faction:
  Level:
  Scoreboard:
  Creator:
  bonkstick: